version: '3'

services:

  consul-enterprise0:
    build: docker/images/consul-enterprise
    image: local/consul-enterprise
    ports:
      - "8080:8080"
      - "8500:8500"
      - "8600:8600"

  # consul-enterprise1:
  #   build: docker/images/consul-enterprise
  #   image: local/consul-enterprise

  # consul-enterprise2:
  #   build: docker/images/consul-enterprise
  #   image: local/consul-enterprise

  # vault-enterprise0:
  #   build: docker/images/vault-enterprise
  #   image: local/vault-enterprise
  #   ports:
  #     - "8201:8200"
  #   links:
  #     - consul-enterprise0

  # vault-enterprise1:
  #   build: docker/images/vault-enterprise
  #   image: local/vault-enterprise
  #   ports:
  #     - "8202:8200"
  #   links:
  #     - consul-enterprise0

  # vault-enterprise2:
  #   build: docker/images/vault-enterprise
  #   image: local/vault-enterprise
  #   ports:
  #     - "8203:8200"
  #  links:
  #     - consul-enterprise0
