version: '3'

services:

  consul:
    image: consul:0.8.5
    ports:
      - "8080:8080"
      - "8500:8500"
      - "8600:8600"

  vault-enterprise0:
    build: docker/images/vault-enterprise
    image: vault-enterprise
    ports:
      - "8201:8200"
    links:
      - postgres
      - consul

  vault-enterprise1:
    build: docker/images/vault-enterprise
    image: vault-enterprise
    ports:
      - "8202:8200"
    links:
      - postgres
      - consul

  vault-enterprise2:
    build: docker/images/vault-enterprise
    image: vault-enterprise
    ports:
      - "8203:8200"
    links:
      - postgres
      - consul
