version: '3'
services:
  vault-enterprise0:
    build: docker/images/vault-enterprise
    image: vault-enterprise
    ports:
      - "8201:8200"
    links:
      - postgres

  vault-enterprise1:
    build: docker/images/vault-enterprise
    image: vault-enterprise
    ports:
      - "8202:8200"
    links:
      - postgres

  vault-enterprise2:
    build: docker/images/vault-enterprise
    image: vault-enterprise
    ports:
      - "8203:8200"
    links:
      - postgres
