version: '3'

services:

  consul-enterprise0:
    build: ../../images/consul-vault-enterprise
    image: local/consul-vault-enterprise
    container_name: consul-enterprise0
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/consul agent -server -bootstrap -ui -data-dir /var/hashicorp/consul
      -disable-host-node-id -client 0.0.0.0 -raft-protocol 3
    ports:
      - "8500:8500"
      - "8600:8600"

  consul-enterprise1:
    build: ../../images/consul-vault-enterprise
    image: local/consul-vault-enterprise
    container_name: consul-enterprise1
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/consul agent -server -data-dir /var/hashicorp/consul -disable-host-node-id
      -client 0.0.0.0 -join consul-enterprise0 -client 0.0.0.0 -raft-protocol 3
    links:
      - consul-enterprise0

  consul-enterprise2:
    build: ../../images/consul-vault-enterprise
    image: local/consul-vault-enterprise
    container_name: consul-enterprise2
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/consul agent -server -data-dir /var/hashicorp/consul -disable-host-node-id
      -client 0.0.0.0 -join consul-enterprise0 -client 0.0.0.0 -raft-protocol 3
    links:
      - consul-enterprise0

  consul-enterprise3:
    build: ../../images/consul-vault-enterprise
    image: local/consul-vault-enterprise
    container_name: consul-enterprise3
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/consul agent -server -data-dir /var/hashicorp/consul -disable-host-node-id
      -client 0.0.0.0 -join consul-enterprise0 -client 0.0.0.0 -raft-protocol 3
    links:
      - consul-enterprise0

  consul-enterprise4:
    build: ../../images/consul-vault-enterprise
    image: local/consul-vault-enterprise
    container_name: consul-enterprise4
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/consul agent -server -data-dir /var/hashicorp/consul -disable-host-node-id
      -client 0.0.0.0 -join consul-enterprise0 -client 0.0.0.0 -raft-protocol 3
    links:
      - consul-enterprise0

  vault-enterprise0:
    build: ../../images/consul-vault-enterprise
    image: local/consul-vault-enterprise
    container_name: vault-enterprise0
    ports:
      - "8200:8200"
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/vault server -config /etc/hashicorp/vault/config.hcl
    links:
      - consul-enterprise0
    cap_add:
      - IPC_LOCK

  vault-enterprise1:
    build: ../../images/consul-vault-enterprise
    image: local/consul-vault-enterprise
    container_name: vault-enterprise1
    ports:
      - "8201:8200"
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/vault server -config /etc/hashicorp/vault/config.hcl
    links:
      - consul-enterprise0
    cap_add:
      - IPC_LOCK

  vault-enterprise2:
    build: ../../images/consul-vault-enterprise
    image: local/consul-vault-enterprise
    container_name: vault-enterprise2
    ports:
      - "8202:8200"
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/vault server -config /etc/hashicorp/vault/config.hcl
    links:
      - consul-enterprise0
    cap_add:
      - IPC_LOCK
